local players = player.GetAll()
timer.Create("dax151",10,0,function() players = player.GetAll() end)
local render = render
hook.Add( "PostDrawOpaqueRenderables", "methamphetamine.chams", function()
    --if methamphetamine.screengrab then return end
	render.SetStencilWriteMask( 0xFF )
	render.SetStencilTestMask( 0xFF )
	render.SetStencilReferenceValue( 0 )
	render.SetStencilCompareFunction( STENCIL_ALWAYS )
	render.SetStencilPassOperation( STENCIL_KEEP )
	render.SetStencilFailOperation( STENCIL_KEEP )
	render.SetStencilZFailOperation( STENCIL_KEEP )
	render.ClearStencil()
	render.SetStencilEnable( true )
	render.SetStencilReferenceValue( 1 )
	render.SetStencilCompareFunction( STENCIL_EQUAL )
	render.SetStencilFailOperation( STENCIL_REPLACE )
	for _, ent in ipairs( players ) do ent:DrawModel() end
	render.ClearBuffersObeyStencil( 200,100,90, 255, false )
	render.SetStencilEnable( false )
end )	
--hook.Remove("PostDrawOpaqueRenderables", "methamphetamine.chams")